events {
    worker_connections 1024;
}

http {
    upstream catalogo_service {server svc-catalogo:8091;}
    upstream miembros_service {server svc-miembros:8092;}
    upstream prestamos_service {server svc-prestamos:8093;}

    server {
        listen 80;
        location /api/catalogo/ {
            proxy_pass http://catalogo_service/catalogo/;
            proxy_set_header Host $host;
        }
        location /api/miembros/ {
            proxy_pass http://miembros_service/miembros/;
            proxy_set_header Host $host;
        }
        location /api/prestamos/ {
            proxy_pass http://prestamos_service/prestamos/;
            proxy_set_header Host $host;
        }
    }
}